// <auto-generated />
using System;
using CarRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CarRentalDbContext))]
[Migration("20260306151307_SeedAllDataFinal")]
partial class SeedAllDataFinal
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DailyPrice")
                    .HasColumnType("int");

                b.Property<int>("DistanceKm")
                    .HasColumnType("int");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Cars");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Brand = "Toyota",
                        DailyPrice = 15000,
                        DistanceKm = 110000,
                        LicensePlate = "AA-BB-123",
                        Model = "Corolla",
                        Status = 0
                    },
                    new
                    {
                        Id = 2,
                        Brand = "Tesla",
                        DailyPrice = 45000,
                        DistanceKm = 23000,
                        LicensePlate = "EL-ON-420",
                        Model = "Model 3",
                        Status = 0
                    },
                    new
                    {
                        Id = 3,
                        Brand = "Ford",
                        DailyPrice = 8000,
                        DistanceKm = 180000,
                        LicensePlate = "SIX-767",
                        Model = "Mondeo",
                        Status = 2
                    });
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Invoice", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Amount")
                    .HasColumnType("int");

                b.Property<DateTime>("IssuedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("PaidAt")
                    .HasColumnType("datetime2");

                b.Property<int>("RentalId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RentalId")
                    .IsUnique();

                b.ToTable("Invoices");
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("ApprovedByUserId")
                    .HasColumnType("int");

                b.Property<int>("CarId")
                    .HasColumnType("int");

                b.Property<DateTime?>("ClosedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("GuestEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("GuestName")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("GuestPhone")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("HandedOverAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int?>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ApprovedByUserId");

                b.HasIndex("CarId");

                b.HasIndex("UserId");

                b.ToTable("Rentals");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CarId = 1,
                        EndDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Status = 0,
                        UserId = 2
                    },
                    new
                    {
                        Id = 2,
                        CarId = 3,
                        EndDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        StartDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Status = 0,
                        UserId = 4
                    });
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("RoleType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoleType")
                    .IsUnique();

                b.ToTable("Roles");

                b.HasData(
                    new
                    {
                        Id = 1,
                        RoleType = 2
                    },
                    new
                    {
                        Id = 2,
                        RoleType = 1
                    },
                    new
                    {
                        Id = 3,
                        RoleType = 0
                    });
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Users", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("FirstName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("LastName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Phone")
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("UserName")
                    .IsUnique();

                b.ToTable("Users");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Address = "Admin Street 1",
                        Email = "admin@admin.hu",
                        FirstName = "Admin",
                        LastName = "Admin",
                        Password = "admin123",
                        Phone = "+36206766767",
                        UserName = "admin"
                    },
                    new
                    {
                        Id = 2,
                        Address = "Haszkovó u. 67",
                        Email = "vadjanos67@freemail.hu",
                        FirstName = "Vad",
                        LastName = "János",
                        Password = "viccesjelszo",
                        Phone = "+36306766767",
                        UserName = "VadonJani67"
                    },
                    new
                    {
                        Id = 3,
                        Address = "Fast Street 1",
                        Email = "acsaladazelso@csalad.com",
                        FirstName = "Dom",
                        LastName = "Toretto",
                        Password = "csalad4ever",
                        Phone = "+3612345678",
                        UserName = "DomToretto"
                    },
                    new
                    {
                        Id = 4,
                        Address = "Vágó utca 13",
                        Email = "johnp13@gmail.com",
                        FirstName = "Sertés",
                        LastName = "János",
                        Password = "tehenhus42",
                        Phone = "+36706766767",
                        UserName = "JohnPork13"
                    });
            });

        modelBuilder.Entity("UserRoles", b =>
            {
                b.Property<int>("RolesId")
                    .HasColumnType("int");

                b.Property<int>("UsersId")
                    .HasColumnType("int");

                b.HasKey("RolesId", "UsersId");

                b.HasIndex("UsersId");

                b.ToTable("UserRoles", (string)null);

                b.HasData(
                    new
                    {
                        RolesId = 1,
                        UsersId = 1
                    },
                    new
                    {
                        RolesId = 2,
                        UsersId = 2
                    },
                    new
                    {
                        RolesId = 3,
                        UsersId = 3
                    },
                    new
                    {
                        RolesId = 2,
                        UsersId = 4
                    });
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Invoice", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Rental", "Rental")
                    .WithOne("Invoice")
                    .HasForeignKey("CarRental.Domain.Entities.Invoice", "RentalId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Rental");
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Users", "ApprovedByUser")
                    .WithMany("ApprovedRent")
                    .HasForeignKey("ApprovedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("CarRental.Domain.Entities.Car", "Car")
                    .WithMany("Rentals")
                    .HasForeignKey("CarId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("CarRental.Domain.Entities.Users", "User")
                    .WithMany("Rentals")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("ApprovedByUser");

                b.Navigation("Car");

                b.Navigation("User");
            });

        modelBuilder.Entity("UserRoles", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Role", null)
                    .WithMany()
                    .HasForeignKey("RolesId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CarRental.Domain.Entities.Users", null)
                    .WithMany()
                    .HasForeignKey("UsersId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
            {
                b.Navigation("Rentals");
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.Navigation("Invoice");
            });

        modelBuilder.Entity("CarRental.Domain.Entities.Users", b =>
            {
                b.Navigation("ApprovedRent");

                b.Navigation("Rentals");
            });
#pragma warning restore 612, 618
    }
}
